In [1]:
import numpy as np

In [2]:
X = np.array([[1., -1., 2.],
             [2., 0., 0.],
             [0., 1., -1.]])

In [4]:
from sklearn import preprocessing

In [9]:
X_scaled = preprocessing.scale(X) # makes mean = zero, variance = one, column-wise

In [10]:
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [11]:
print(X_scaled.mean(axis = 0))
print(X_scaled.std(axis = 0))

[0. 0. 0.]
[1. 1. 1.]


In [16]:
scalar = preprocessing.StandardScaler()
scalar.fit(X)
print(X)
print(scalar.transform(X))
print(X.T)
scalar.transform(X.T)

[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
[[ 1.  2.  0.]
 [-1.  0.  1.]
 [ 2.  0. -1.]]


array([[ 0.        ,  2.44948974, -0.26726124],
       [-2.44948974,  0.        ,  0.53452248],
       [ 1.22474487,  0.        , -1.06904497]])